<a href="https://colab.research.google.com/github/C4-H10/Optimasi-Portofolio-Pada-Saham-IDX30-Menggunakan-Capital-Asset-Pricing-Model-CAPM-/blob/main/Optimasi_Portofolio_CAPM_pada_Saham_IDX30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#KONFIGURASI

Data yang akan dianalisis merupakan data harian dengan konfigurasi sebagai berikut :

In [1]:
Tanggal_Mulai = "2025-03-26"
Tanggal_Selesai = "2026-03-26"

LIST_SAHAM = [
    "AADI.JK", "ADRO.JK", "AMRT.JK", "ANTM.JK", "ASII.JK",
    "BBCA.JK", "BBNI.JK", "BBRI.JK", "BMRI.JK", "BRPT.JK",
    "BUMI.JK", "CPIN.JK", "EMTK.JK", "GOTO.JK", "ICBP.JK",
    "INCO.JK", "INDF.JK", "INKP.JK", "ISAT.JK", "JPFA.JK",
    "KLBF.JK", "MBMA.JK", "MDKA.JK", "MEDC.JK", "PGAS.JK",
    "PGEO.JK", "PTBA.JK", "TLKM.JK", "UNTR.JK", "UNVR.JK"
]

#List Suku Bunga BI (BI Rate)
suku_bunga_list = [0.0475,0.0475,0.0475,0.0475,0.0475,0.0475,0.0475,0.05,0.0525,0.055,0.055,0.0575]

Data BI-Rate bisa diakses melalui link berikut https://www.bi.go.id/id/statistik/indikator/BI-Rate.aspx

#IMPORT DATA

##DATA SAHAM

In [2]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.14.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [3]:
import yfinance as yf
import pandas as pd
df = yf.download(LIST_SAHAM,
                 start=Tanggal_Mulai,
                 end=Tanggal_Selesai,
                 auto_adjust=True)['Close']

df.info()

[*********************100%***********************]  30 of 30 completed

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 231 entries, 2025-03-26 to 2026-03-25
Data columns (total 30 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   AADI.JK  231 non-null    float64
 1   ADRO.JK  231 non-null    float64
 2   AMRT.JK  231 non-null    float64
 3   ANTM.JK  231 non-null    float64
 4   ASII.JK  231 non-null    float64
 5   BBCA.JK  231 non-null    float64
 6   BBNI.JK  231 non-null    float64
 7   BBRI.JK  231 non-null    float64
 8   BMRI.JK  231 non-null    float64
 9   BRPT.JK  231 non-null    float64
 10  BUMI.JK  231 non-null    float64
 11  CPIN.JK  231 non-null    float64
 12  EMTK.JK  231 non-null    float64
 13  GOTO.JK  231 non-null    float64
 14  ICBP.JK  231 non-null    float64
 15  INCO.JK  231 non-null    float64
 16  INDF.JK  231 non-null    float64
 17  INKP.JK  231 non-null    float64
 18  ISAT.JK  231 non-null    float64
 19  JPFA.JK  231 non-null    float64
 20  KLBF.JK  231 non-null    float64
 21  MBMA.JK  231 non-null    float64
 22  MDKA.JK  231 non-null    float64
 23  MEDC.JK  231 non-null    float64
 24  PGAS.JK  231 non-null    float64
 25  PGEO.JK  231 non-null    float64
 26  PTBA.JK  231 non-null    float64
 27  TLKM.JK  231 non-null    float64
 28  UNTR.JK  231 non-null    float64
 29  UNVR.JK  231 non-null    float64
dtypes: float64(30)
memory usage: 55.9 KB

In [4]:
df.head()

Ticker,AADI.JK,ADRO.JK,AMRT.JK,ANTM.JK,ASII.JK,BBCA.JK,BBNI.JK,BBRI.JK,BMRI.JK,BRPT.JK,...,KLBF.JK,MBMA.JK,MDKA.JK,MEDC.JK,PGAS.JK,PGEO.JK,PTBA.JK,TLKM.JK,UNTR.JK,UNVR.JK
Date,,,,,,,,,,,,,,,,,,,,,
2025-03-26,6170.670898,1568.816895,1983.831665,1571.742188,4419.839355,8113.821777,3590.144775,3643.608643,4586.586914,680.0,...,1074.451660,302.0,1450.0,989.724243,1400.278198,789.660706,2227.146729,2261.849365,21488.732422,1162.857788
2025-03-27,6123.746094,1573.079956,2023.310913,1557.453613,4530.334961,8090.027344,3581.697266,3689.153809,4631.116699,710.0,...,1108.638794,300.0,1430.0,984.919739,1404.795288,775.215698,2236.020020,2234.039795,21534.453125,1186.302490
2025-04-08,5396.404297,1402.556396,2003.571289,1333.599487,4125.183105,7399.995605,3404.302002,3315.683838,4159.099121,645.0,...,1030.496826,256.0,1220.0,932.070374,1305.420654,736.695679,2147.289062,2122.801270,18379.724609,1106.590576
2025-04-09,5396.404297,1406.819580,2043.050537,1405.042236,4254.095215,7542.761230,3412.749512,3306.574951,4194.723145,600.0,...,1079.335449,242.0,1040.0,898.438965,1346.073853,741.510681,2182.781250,2150.610840,18791.210938,1083.145752
2025-04-10,5631.030762,1449.450439,2260.186279,1552.690796,4336.967285,7828.291504,3598.592285,3461.428223,4475.261719,655.0,...,1118.406494,262.0,1220.0,975.310791,1400.278198,775.215698,2377.989502,2178.420654,19934.228516,1205.058350

In [5]:
df.to_excel('data_idx30.xlsx', index=True)

In [6]:
# Dataframe Return Saham (Log Return)
import numpy as np

return_saham = np.log(df / df.shift(1))
return_saham = return_saham.dropna()
return_saham.head()

Ticker,AADI.JK,ADRO.JK,AMRT.JK,ANTM.JK,ASII.JK,BBCA.JK,BBNI.JK,BBRI.JK,BMRI.JK,BRPT.JK,...,KLBF.JK,MBMA.JK,MDKA.JK,MEDC.JK,PGAS.JK,PGEO.JK,PTBA.JK,TLKM.JK,UNTR.JK,UNVR.JK
Date,,,,,,,,,,,,,,,,,,,,,
2025-03-27,-0.007634,0.002714,0.019705,-0.009132,0.024693,-0.002937,-0.002356,0.012423,0.009662,0.043172,...,0.031323,-0.006645,-0.013889,-0.004866,0.003221,-0.018462,0.003976,-0.012371,0.002125,0.019961
2025-04-08,-0.126441,-0.114739,-0.009804,-0.155171,-0.093685,-0.089153,-0.050797,-0.106733,-0.107500,-0.096015,...,-0.073092,-0.158605,-0.158824,-0.055152,-0.073366,-0.050966,-0.040491,-0.051075,-0.158406,-0.069558
2025-04-09,0.000000,0.003035,0.019513,0.052186,0.030772,0.019109,0.002478,-0.002751,0.008529,-0.072321,...,0.046304,-0.056240,-0.159630,-0.036750,0.030667,0.006515,0.016394,0.013015,0.022141,-0.021414
2025-04-10,0.042560,0.029853,0.101003,0.099922,0.019293,0.037156,0.053024,0.045768,0.064737,0.087706,...,0.035559,0.079407,0.159630,0.082097,0.039479,0.044452,0.085656,0.012848,0.059049,0.106658
2025-04-11,-0.016807,0.008785,-0.035559,0.036149,0.000000,0.006061,0.030060,0.010635,0.014815,0.015152,...,0.030110,-0.038915,0.067352,0.000000,0.019170,0.000000,0.000000,-0.008547,0.002291,0.019268

##DATA IHSG

In [7]:
ihsg = yf.download("^JKSE",
                   start=Tanggal_Mulai,
                   end=Tanggal_Selesai,
                   auto_adjust=True)['Close']

ihsg.to_excel('ihsg.xlsx', index=True)
ihsg.head()

[*********************100%***********************]  1 of 1 completed

Ticker            ^JKSE
Date
2025-03-26  6472.355957
2025-03-27  6510.620117
2025-04-08  5996.142090
2025-04-09  5967.987793
2025-04-10  6254.023926

In [8]:
# Dataframe Return IHSG (Log Return)
return_IHSG = np.log(ihsg / ihsg.shift(1))
return_IHSG = return_IHSG.dropna()
return_IHSG.head()

Ticker         ^JKSE
Date
2025-03-27  0.005895
2025-04-08 -0.082318
2025-04-09 -0.004706
2025-04-10  0.046815
2025-04-11  0.001311

#PERHITUNGAN BOBOT PORTOFOLIO

### **Penjelasan Variabel**

1.  **RATA RATA**: Merupakan nilai rata-rata pengembalian harian dari masing-masing saham selama periode observasi. Ini merepresentasikan ekspektasi keuntungan (reward) yang diberikan aset tersebut di masa lalu.
2.  **VARIAN**: Mengukur sejauh mana data return tersebar dari nilai rata-ratanya. Dalam investasi, varian digunakan sebagai proksi dari risiko total (total risk) saham tersebut. Semakin besar variannya, semakin tinggi fluktuasi harganya.
3. **BETA**: Indikator risiko sistematis yang mengukur sensitivitas return saham terhadap pergerakan pasar (IHSG).
- $\beta = 1$: Saham bergerak sejalan dengan pasar.
- $\beta > 1$: Saham lebih volatil dari pasar (Agresif).
- $\beta < 1$: Saham kurang volatil dibanding pasar (Defensif).
4.  **ALFA ($\alpha$)**: Komponen imbal hasil yang bersifat independen atau tidak dipengaruhi oleh pergerakan pasar secara keseluruhan.
5.  **E(Ri) CAPM**: Expected Return berdasarkan model CAPM. Dihitung dengan: $$E(R_i) = R_f + \beta_i (E(R_m) - R_f)$$

6. *Excess Return**: Selisih antara return harapan ($E(R_i)$) dengan tingkat bunga bebas risiko ($R_f$). Ini menunjukkan tambahan keuntungan yang diharapkan investor karena memilih aset berisiko dibandingkan menyimpan uang di instrumen yang aman (seperti suku bunga BI).

7. **Bobot (Wi)**: Proporsi alokasi modal pada masing-masing saham dalam portofolio optimal

In [9]:
market_return = return_IHSG.iloc[:, 0]
var_market_sample = market_return.var(ddof=1)
var_market_pop = market_return.var(ddof=0)

rata_rata_suku_bunga = np.mean(suku_bunga_list)
rf = rata_rata_suku_bunga / len(return_saham)
print(f"Rata-rata harian suku bunga BI : {rf}")

betas = {}
for col in return_saham.columns:
    cov_p = np.cov(return_saham[col], market_return, ddof=0)[0][1]
    betas[col] = cov_p / var_market_sample

beta_series = pd.Series(betas)
rata_rata = return_saham.mean()
varian_saham = return_saham.var(ddof=0)
eri = rf + (beta_series * (market_return.mean() - rf))

sigma = return_saham.cov()
inv_sigma = np.linalg.inv(sigma)

excess_return = eri - rf

pembilang = inv_sigma.dot(excess_return)

ones = np.ones(len(eri))
penyebut = ones.T.dot(pembilang)

bobot_wi = pembilang / penyebut

summary_df = pd.DataFrame({
    'RATA RATA': rata_rata,
    'VARIAN': varian_saham,
    'SUM': return_saham.sum(),
    'BETA': beta_series,
    'ALFA': rata_rata - (beta_series * market_return.mean()),
    'E(Ri) CAPM': eri,
    'Excess_Return': excess_return,
    'Bobot (Wi)': bobot_wi
})

summary_df.index.name = 'Saham'
print(f"Total Bobot Wi: {summary_df['Bobot (Wi)'].sum()}")
summary_df

Rata-rata harian suku bunga BI : 0.00021829710144927536
Total Bobot Wi: 1.0000000000000002

,RATA RATA,VARIAN,SUM,BETA,ALFA,E(Ri) CAPM,Excess_Return,Bobot (Wi)
Saham,,,,,,,,
AADI.JK,0.002582,0.000723,0.593872,0.476670,0.002332,0.000364,0.000146,-0.032594
ADRO.JK,0.002246,0.000731,0.516662,0.840660,0.001805,0.000476,0.000257,0.017803
AMRT.JK,-0.001144,0.000678,-0.263036,0.695596,-0.001508,0.000431,0.000213,0.049900
ANTM.JK,0.003627,0.001385,0.834289,1.021817,0.003091,0.000531,0.000313,0.031445
ASII.JK,0.001743,0.000567,0.400966,0.820530,0.001313,0.000470,0.000251,0.068029
BBCA.JK,-0.000891,0.000308,-0.204893,0.787487,-0.001304,0.000459,0.000241,0.072670
BBNI.JK,0.000513,0.000346,0.118052,0.659306,0.000167,0.000420,0.000202,0.023680
BBRI.JK,-0.000125,0.000381,-0.028848,0.907888,-0.000602,0.000496,0.000278,0.187176
BMRI.JK,0.000349,0.000426,0.080284,0.982540,-0.000166,0.000519,0.000301,0.046256
BRPT.JK,0.003155,0.002101,0.725700,1.958236,0.002128,0.000818,0.000600,0.084396
BUMI.JK,0.004003,0.002829,0.920725,1.855332,0.003030,0.000786,0.000568,0.046576
CPIN.JK,-0.000246,0.000500,-0.056594,0.583806,-0.000552,0.000397,0.000179,0.005482
EMTK.JK,0.002243,0.002237,0.515861,1.713849,0.001344,0.000743,0.000525,0.032111
GOTO.JK,-0.001950,0.000933,-0.448549,1.052321,-0.002502,0.000540,0.000322,0.060360
ICBP.JK,-0.001527,0.000329,-0.351314,0.507250,-0.001793,0.000374,0.000155,0.058136
INCO.JK,0.004011,0.001546,0.922539,1.426415,0.003263,0.000655,0.000437,0.012560
INDF.JK,-0.000454,0.000341,-0.104478,0.282572,-0.000602,0.000305,0.000087,0.007075
INKP.JK,0.003051,0.001200,0.701768,1.389240,0.002323,0.000644,0.000425,0.046160
ISAT.JK,0.001813,0.001113,0.417071,1.219449,0.001174,0.000592,0.000373,0.026377
JPFA.JK,0.000749,0.000976,0.172212,0.679545,0.000392,0.000426,0.000208,0.000588
KLBF.JK,-0.000334,0.000709,-0.076823,0.629391,-0.000664,0.000411,0.000193,-0.015630
MBMA.JK,0.003837,0.002633,0.882618,1.729578,0.002930,0.000748,0.000530,0.003720
MDKA.JK,0.003428,0.001951,0.788457,1.432394,0.002677,0.000657,0.000439,0.016185
MEDC.JK,0.002478,0.000829,0.569945,0.592157,0.002167,0.000400,0.000181,0.033445
PGAS.JK,0.001451,0.000460,0.333719,0.591503,0.001141,0.000399,0.000181,-0.014227
PGEO.JK,0.001005,0.001099,0.231139,1.085373,0.000436,0.000551,0.000332,0.021043
PTBA.JK,0.001521,0.000263,0.349851,0.532354,0.001242,0.000381,0.000163,0.009911
TLKM.JK,0.001642,0.000617,0.377740,0.987585,0.001124,0.000521,0.000302,0.079564
UNTR.JK,0.001562,0.000632,0.359174,0.867549,0.001107,0.000484,0.000266,0.014312
UNVR.JK,0.002214,0.001101,0.509227,0.824551,0.001782,0.000471,0.000252,0.007490

In [10]:
print(f"Jumlah saham yang terpilih sebanyak : {len(summary_df)} saham")
print(summary_df[["Bobot (Wi)"]].sort_values(by="Bobot (Wi)", ascending=False))

Jumlah saham yang terpilih sebanyak : 30 saham
         Bobot (Wi)
Saham
BBRI.JK    0.187176
BRPT.JK    0.084396
TLKM.JK    0.079564
BBCA.JK    0.072670
ASII.JK    0.068029
GOTO.JK    0.060360
ICBP.JK    0.058136
AMRT.JK    0.049900
BUMI.JK    0.046576
BMRI.JK    0.046256
INKP.JK    0.046160
MEDC.JK    0.033445
EMTK.JK    0.032111
ANTM.JK    0.031445
ISAT.JK    0.026377
BBNI.JK    0.023680
PGEO.JK    0.021043
ADRO.JK    0.017803
MDKA.JK    0.016185
UNTR.JK    0.014312
INCO.JK    0.012560
PTBA.JK    0.009911
UNVR.JK    0.007490
INDF.JK    0.007075
CPIN.JK    0.005482
MBMA.JK    0.003720
JPFA.JK    0.000588
PGAS.JK   -0.014227
KLBF.JK   -0.015630
AADI.JK   -0.032594

#KINERJA PORTOFOLIO

**Ekspektasi Return Portofolio** : <br>
rata-rata tingkat keuntungan yang diharapkan setiap hari
<br><br>
**Beta Portofolio** : <br>
Jika beta > 1 portofolio lebih volatil dibandingkan pasar.<br>
Jika beta < 1 portofolio lebih stabil. <br>
Jika beta = 1 maka portofolio bergerak mengikuti pergerakan pasar (IHSG).
<br><br>
**Indeks Treynor** :<br>
Jika Indeks Treynor portofolio > Indeks Treynor IHSG, maka portofolio yang disusun sudah optimal

In [11]:
# Rata-rata Return IHSG
rata_rata_ihsg = return_IHSG.mean().iloc[0]

# Suku Bunga Bebas Risiko (Rf)
risk_free = rf

# Beta IHSG
beta_market = 1.0

# Rumus Treynor IHSG
treynor_ihsg = (rata_rata_ihsg - risk_free) / beta_market

# Ekspektasi Return Portofolio
return_portofolio = (summary_df['Bobot (Wi)'] * summary_df['E(Ri) CAPM']).sum()

# Beta Portofolio
beta_portofolio = (summary_df['Bobot (Wi)'] * summary_df['BETA']).sum()

# Rumus Treynor Portofolio
treynor_portofolio = (return_portofolio - risk_free) / beta_portofolio

print("=== KINERJA PORTOFOLIO (INDEKS TREYNOR) ===")
print(f"Return Harian IHSG         : {rata_rata_ihsg:.6f}")
print(f"Return Harian Portofolio   : {return_portofolio:.6f}")
print("-" * 45)
print(f"Beta Portofolio            : {beta_portofolio:.6f}")
print("-" * 45)
print(f"Indeks Treynor IHSG        : {treynor_ihsg:.10f}")
print(f"Indeks Treynor Portofolio  : {treynor_portofolio:.10f}")
print("-" * 45)

=== KINERJA PORTOFOLIO (INDEKS TREYNOR) ===
Return Harian IHSG         : 0.000524
Return Harian Portofolio   : 0.000551
---------------------------------------------
Beta Portofolio            : 1.086299
---------------------------------------------
Indeks Treynor IHSG        : 0.0003061581
Indeks Treynor Portofolio  : 0.0003061581
---------------------------------------------

In [12]:
std_dev = np.sqrt(summary_df['VARIAN'])
summary_df['Sharpe Ratio'] = summary_df['Excess_Return'] / std_dev
summary_df['Treynor Ratio'] = summary_df['Excess_Return'] / summary_df['BETA']
summary_df['Indeks Jensen'] = summary_df['ALFA']
indeks = summary_df[['Sharpe Ratio', 'Treynor Ratio', 'Indeks Jensen']]
indeks

         Sharpe Ratio  Treynor Ratio  Indeks Jensen
Saham
AADI.JK      0.005427       0.000306       0.002332
ADRO.JK      0.009522       0.000306       0.001805
AMRT.JK      0.008179       0.000306      -0.001508
ANTM.JK      0.008405       0.000306       0.003091
ASII.JK      0.010552       0.000306       0.001313
BBCA.JK      0.013728       0.000306      -0.001304
BBNI.JK      0.010849       0.000306       0.000167
BBRI.JK      0.014247       0.000306      -0.000602
BMRI.JK      0.014573       0.000306      -0.000166
BRPT.JK      0.013080       0.000306       0.002128
BUMI.JK      0.010680       0.000306       0.003030
CPIN.JK      0.007994       0.000306      -0.000552
EMTK.JK      0.011093       0.000306       0.001344
GOTO.JK      0.010546       0.000306      -0.002502
ICBP.JK      0.008565       0.000306      -0.001793
INCO.JK      0.011108       0.000306       0.003263
INDF.JK      0.004684       0.000306      -0.000602
INKP.JK      0.012277       0.000306       0.002323
ISAT.JK      0.011192       0.000306       0.001174
JPFA.JK      0.006660       0.000306       0.000392
KLBF.JK      0.007235       0.000306      -0.000664
MBMA.JK      0.010320       0.000306       0.002930
MDKA.JK      0.009927       0.000306       0.002677
MEDC.JK      0.006297       0.000306       0.002167
PGAS.JK      0.008443       0.000306       0.001141
PGEO.JK      0.010023       0.000306       0.000436
PTBA.JK      0.010054       0.000306       0.001242
TLKM.JK      0.012175       0.000306       0.001124
UNTR.JK      0.010567       0.000306       0.001107
UNVR.JK      0.007609       0.000306       0.001782

# PENGAMBILAN KEPUTUSAN

1. **Indeks Sharpe**: Saham dengan nilai Indeks Sharpe tinggi dapat memberikan imbal hasil yang lebih kompensasif terhadap fluktuasi harganya.

2. **Indeks Treynor**: Portofolio optimal jika Indeks Treynor portofolio lebih besar dari Indeks Treynor harga pasar (IHSG) .

3. **Indeks Jensen**: Saham dengan nilai Indeks Jensen positif maka saham tersebut masuk dalam saham yang sedang mengalami *undervalue*.

##Indeks Sharpe yang diurutkan + jensen positif

In [13]:
indeks[indeks['Indeks Jensen'] > 0].sort_values(by='Sharpe Ratio', ascending=False)

         Sharpe Ratio  Treynor Ratio  Indeks Jensen
Saham
BRPT.JK      0.013080       0.000306       0.002128
INKP.JK      0.012277       0.000306       0.002323
TLKM.JK      0.012175       0.000306       0.001124
ISAT.JK      0.011192       0.000306       0.001174
INCO.JK      0.011108       0.000306       0.003263
EMTK.JK      0.011093       0.000306       0.001344
BBNI.JK      0.010849       0.000306       0.000167
BUMI.JK      0.010680       0.000306       0.003030
UNTR.JK      0.010567       0.000306       0.001107
ASII.JK      0.010552       0.000306       0.001313
MBMA.JK      0.010320       0.000306       0.002930
PTBA.JK      0.010054       0.000306       0.001242
PGEO.JK      0.010023       0.000306       0.000436
MDKA.JK      0.009927       0.000306       0.002677
ADRO.JK      0.009522       0.000306       0.001805
PGAS.JK      0.008443       0.000306       0.001141
ANTM.JK      0.008405       0.000306       0.003091
UNVR.JK      0.007609       0.000306       0.001782
JPFA.JK      0.006660       0.000306       0.000392
MEDC.JK      0.006297       0.000306       0.002167
AADI.JK      0.005427       0.000306       0.002332

Note : Jika sudah mendapatkan beberapa saham yang sudah diseleksi maka lakukan analisis ulang dengan mengubah LIST_SAHAM pada bagian konfigurasi dengan saham yang terlampir saja